"""empty message

Revision ID: 1669ec756a61
Revises: 5847b5577451
Create Date: 2021-03-22 09:25:52.489872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1669ec756a61'
down_revision = '5847b5577451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'followers', ['id'])
    op.drop_constraint('followers_follower_id_fkey', 'followers', type_='foreignkey')
    op.drop_constraint('followers_followed_id_fkey', 'followers', type_='foreignkey')
    op.drop_column('followers', 'followed_id')
    op.drop_column('followers', 'follower_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('followers', sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('followers_followed_id_fkey', 'followers', 'user', ['followed_id'], ['id'])
    op.create_foreign_key('followers_follower_id_fkey', 'followers', 'user', ['follower_id'], ['id'])
    op.drop_constraint(None, 'followers', type_='unique')
    op.drop_column('followers', 'id')
    # ### end Alembic commands ###
