"""empty message

Revision ID: 39782c40569e
Revises: 00d228c0a429
Create Date: 2021-03-22 10:05:36.696363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39782c40569e'
down_revision = '00d228c0a429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.add_column('followers', sa.Column('follower_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'followers', 'user', ['follower_id'], ['id'])
    op.drop_column('followers', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_column('followers', 'follower_id')
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###
