"""empty message

Revision ID: 5847b5577451
Revises: c550103582ae
Create Date: 2021-03-19 16:06:36.783454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5847b5577451'
down_revision = 'c550103582ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart', ['id'])
    op.create_unique_constraint(None, 'product', ['id'])
    op.create_unique_constraint(None, 'song', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'song', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'cart', type_='unique')
    # ### end Alembic commands ###
