"""empty message

Revision ID: 601faed5cfe2
Revises: 39782c40569e
Create Date: 2021-03-22 18:35:54.620303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601faed5cfe2'
down_revision = '39782c40569e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('song_artist', sa.String(), nullable=True))
    op.add_column('product', sa.Column('song_name', sa.String(), nullable=True))
    op.drop_column('product', 'name')
    op.drop_column('product', 'description')
    op.add_column('song', sa.Column('song_name_artist_combined', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'song_name_artist_combined')
    op.add_column('product', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product', 'song_name')
    op.drop_column('product', 'song_artist')
    # ### end Alembic commands ###
