"""empty message

Revision ID: 658d804f95af
Revises: 1070e3107aed
Create Date: 2021-03-24 13:59:42.067798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658d804f95af'
down_revision = '1070e3107aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'song', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='unique')
    # ### end Alembic commands ###
