"""empty message

Revision ID: ccd39f619cb1
Revises: 658d804f95af
Create Date: 2021-03-25 10:12:53.050318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd39f619cb1'
down_revision = '658d804f95af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_name', sa.String(), nullable=True),
    sa.Column('song_rank', sa.Integer(), nullable=True),
    sa.Column('song_artist', sa.String(), nullable=True),
    sa.Column('song_this_week', sa.String(), nullable=True),
    sa.Column('song_last_week', sa.String(), nullable=True),
    sa.Column('song_artist_peak_rank', sa.String(), nullable=True),
    sa.Column('song_artist_weeks_on_chart', sa.String(), nullable=True),
    sa.Column('song_picture', sa.String(), nullable=True),
    sa.Column('start_of_week_date', sa.DateTime(), nullable=False),
    sa.Column('song_name_artist_combined', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
